import React from 'react'
export const metadata = {
  title: "Create User",
  description: "Generated by create next app",
};
const CreateUser = () => {
  return (
    <div className="h-screen">user details</div>
  )
}

export default CreateUser