import React from 'react'
export const metadata = {
  title: "Next App || Categories ",
  description: "Generated by create next app",
};
const CategoriesPage = () => {
  return (
    <div>soup, coffee , desert , salad</div>
  )
}

export default CategoriesPage