import React from 'react'
import MealsPage from './pegs'
export const metadata = {
  title: " Categories Page",
  description: "Generated by create next app"
}
const CategoriesPage = () => {
  return (
    <div><MealsPage/> </div>
  )
}

export default CategoriesPage